# Email to which errors will be sent
email: "ayang@lncrna.caltech.edu"

# Path to barcoding config file
bID: "settings_mixed/config_mixed.txt"
# Path to barcoding format file
# format: "example_format.txt"
# Path to samples JSON file, e.g., as produced with the fastq2json.py script
samples: "settings_mixed/samples_full.json"

# Scripts directory
scripts_dir: "scripts/"
# Output directory
output_dir: "/central/scratchio/mblanco/albert"
# Temporary directory
temp_dir: "/central/scratch/"

# Conda environment: either a path to a conda environment YAML file ("*.yml" or "*.yaml")
# or the name of an existing conda environment
conda_env: "chipdip"

# Path to chromosome name map file
path_chrom_map: "chrom_map.txt"

# Number of chunks to split FASTQ reads into for parallel processing
num_chunks: 10

# Files for cutadapt
cutadapt_dpm: "assets/dpm96.fasta"
cutadapt_oligos: "assets/bpm.fasta"

# Mask used for filtering DNA reads
# e.g., "assets/blacklist_mm10.bed" or "assets/blacklist_hg38.bed"
mask: "assets/blacklist_mm10.bed"

#Currently "mm10" and "hg38" available
assembly: "mm10"

# Bowtie2 indexes for aligning DNA reads
# e.g., "assets/index_hg38/GRCh38_noalt_as" or "assets/index_mm10/mm10"
bowtie2_index_dna: "/central/scratchio/mblanco/albert/index_mm10/index_mm10/mm10"

#Bowtie2 Indexes
bowtie2_index_rna:
    hg38: "/groups/guttman/jguo/genomes/ncRNA_bt2/ncRNA"
    mm10: "/groups/guttman/jguo/genomes/mm10_ncRNA_bt2/mm10_ncRNA"

# Generate BAM files for individual targets
generate_splitbams: true
min_oligos: 2
proportion: 0.8
max_size: 10000

# Merge cluster files and BAM files for individual targets across samples
merge_samples: true

# Binsize for generating BigWigs for individual targets merged across samples
# - only relevant if generate_splitbams is true
# - Set to false to skip BigWig generation
binsize: 1000

#Star Indexes
star_index:
    mm10: "/groups/guttman/genomes/mus_musculus/GRCm38/star"
    hg38: "/groups/guttman/genomes/homo_sapiens/hg38"

choose_dna_rna: "dna, rna"