#email to which errors will be sent
email: ""
#Location of the config file for barcodeIdentification
bID: "settings_rna/config_rna.txt"
#Location of the samples json file produced with the fastq2json.py script 
samples: "settings_rna/samples_rna.json"
#Output directory  
output_dir: ""
# Scripts directory
scripts_dir: "./scripts/"
#Temporary directory
temp_dir: "/central/scratch/"
#Currently "mm10" and "hg38" available
assembly: "hg38"
#Number of barcodes used
num_tags: "7"
#Number of chunks to split fastq
num_chunks: 2
#File for cutadapt
cutadapt_oligos: "oligo2_reverse.fasta"
#Bowtie2 Indexes
bowtie2_index_rna:
    hg38: "/groups/guttman/jguo/genomes/ncRNA_bt2/ncRNA"
    mm10: "/groups/guttman/jguo/genomes/mm10_ncRNA_bt2/mm10_ncRNA"
#Star Indexes
star_index:
    mm10: "/groups/guttman/genomes/mus_musculus/GRCm38/star"
    hg38: "/groups/guttman/genomes/homo_sapiens/hg38"

# Generate BAM files for individual targets
generate_splitbams: true
min_oligos: 2
proportion: 0.8
max_size: 10000

conda_env: "chipdip"
choose_dna_rna: "rna"
single_end: true
